name: Check changes
on:
  push:
    branches:
      - "*"
      - "**"
  pull_request:
    branches:
      - "master"
jobs:
  
  denotest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [ "1.23.X", "1.X.X" ]
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*deps.ts') }}
      - name: Run tests
        run: deno task test --doc
  
  denocheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "vx.x.x"
      - name: Run format and lint checks
        run: deno task check
  
  denocov:
    runs-on: ubuntu-latest
    needs: [ "denotest", "denocheck" ]
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.24.X"
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*deps.ts') }}
      - name: Run tests
        run: deno task coverage
      - name: Upload lcov file
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-lcov
          path: "*.lcov"
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: coverage.lcov
          minimum-coverage: 85
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
